// Command genruleinventory generates or verifies the pinned XRechnung rule
// inventory. It deliberately consumes only Schematron source files, never the
// Java reference validator.
package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/jxsl13/einvoice/internal/ruleinventory"
)

type parityManifest struct {
	Dependencies struct {
		Schematron struct {
			Repository string `json:"repository"`
			URL        string `json:"url"`
			Version    string `json:"version"`
			SHA256     string `json:"sha256"`
			License    string `json:"license"`
		} `json:"xrechnungSchematron"`
	} `json:"dependencies"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genruleinventory:", err)
		os.Exit(1)
	}
}

func run() error {
	var archivePath, manifestPath, outputPath string
	var verify bool
	flag.StringVar(&archivePath, "archive", "", "path to the pinned XRechnung Schematron ZIP")
	flag.StringVar(&manifestPath, "manifest", ".github/dependencies/parity.json", "pinned dependency manifest")
	flag.StringVar(&outputPath, "out", "conformance/xrechnung-3.0.2-rules.json", "inventory output")
	flag.BoolVar(&verify, "verify", false, "compare generated bytes with the existing output")
	flag.Parse()
	if archivePath == "" {
		return errors.New("-archive is required")
	}

	manifestData, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("read dependency manifest: %w", err)
	}
	var manifest parityManifest
	decoder := json.NewDecoder(bytes.NewReader(manifestData))
	if err := decoder.Decode(&manifest); err != nil {
		return fmt.Errorf("parse dependency manifest: %w", err)
	}
	reference := manifest.Dependencies.Schematron
	root, cleanup, err := materializeSchematron(archivePath, reference.SHA256)
	if err != nil {
		return err
	}
	defer cleanup()

	ciiPath := filepath.Join(root, "cii", "XRechnung-CII-validation.sch")
	ublPath := filepath.Join(root, "ubl", "XRechnung-UBL-validation.sch")
	ciiDigest, err := sourceDigest(ciiPath)
	if err != nil {
		return err
	}
	ublDigest, err := sourceDigest(ublPath)
	if err != nil {
		return err
	}
	inventory, err := ruleinventory.Generate(ruleinventory.Request{
		Root: root, Phase: "xrechnung-model", Profile: "XRechnung", ProfileVersion: "3.0.2", RuleVersion: reference.Version,
		Archive: ruleinventory.Archive{Repository: reference.Repository, URL: reference.URL, Version: reference.Version, SHA256: reference.SHA256, License: reference.License},
		Sources: []ruleinventory.SyntaxSource{
			{Syntax: "cii", Path: "cii/XRechnung-CII-validation.sch", SHA256: ciiDigest},
			{Syntax: "ubl", Path: "ubl/XRechnung-UBL-validation.sch", SHA256: ublDigest},
		},
	})
	if err != nil {
		return err
	}
	inventory.Capabilities = []ruleinventory.Capability{
		{Group: "infrastructure", Supported: true},
		{Group: "standard", Supported: true},
		{Group: "peppol", Supported: true},
		{Group: "extension", Supported: false, Reason: "profile is explicitly unsupported by the stable rule pack"},
		{Group: "cvd", Supported: false, Reason: "profile is explicitly unsupported by the stable rule pack"},
	}
	data, err := ruleinventory.Marshal(inventory)
	if err != nil {
		return err
	}
	if verify {
		existing, err := os.ReadFile(outputPath)
		if err != nil {
			return fmt.Errorf("read checked-in inventory: %w", err)
		}
		if !bytes.Equal(existing, data) {
			return errors.New("checked-in inventory differs from pinned Schematron sources")
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(outputPath, data, 0o644); err != nil {
		return fmt.Errorf("write inventory: %w", err)
	}
	return nil
}

func sourceDigest(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("read source member: %w", err)
	}
	defer func() { _ = file.Close() }()
	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", fmt.Errorf("digest source member: %w", err)
	}
	return fmt.Sprintf("%x", hash.Sum(nil)), nil
}

const maxArchiveBytes = 32 << 20

var schematronMembers = []string{
	"schematron/common.sch",
	"schematron/cii/XRechnung-CII-validation.sch",
	"schematron/ubl/XRechnung-UBL-validation.sch",
}

func materializeSchematron(archivePath, expectedDigest string) (string, func(), error) {
	archive, err := os.Open(archivePath)
	if err != nil {
		return "", func() {}, fmt.Errorf("open Schematron archive: %w", err)
	}
	defer func() { _ = archive.Close() }()
	info, err := archive.Stat()
	if err != nil {
		return "", func() {}, fmt.Errorf("stat Schematron archive: %w", err)
	}
	if !info.Mode().IsRegular() || info.Size() > maxArchiveBytes {
		return "", func() {}, errors.New("schematron archive is not a bounded regular file")
	}
	hash := sha256.New()
	if _, err := io.Copy(hash, archive); err != nil {
		return "", func() {}, fmt.Errorf("digest Schematron archive: %w", err)
	}
	actualDigest := fmt.Sprintf("%x", hash.Sum(nil))
	if len(expectedDigest) != sha256.Size*2 || !strings.EqualFold(actualDigest, expectedDigest) {
		return "", func() {}, fmt.Errorf("schematron archive digest mismatch: got %s", actualDigest)
	}

	reader, err := zip.OpenReader(archivePath)
	if err != nil {
		return "", func() {}, fmt.Errorf("open Schematron ZIP: %w", err)
	}
	defer func() { _ = reader.Close() }()
	wanted := make(map[string]bool, len(schematronMembers))
	for _, name := range schematronMembers {
		wanted[name] = false
	}
	temporary, err := os.MkdirTemp("", "einvoice-rule-inventory-")
	if err != nil {
		return "", func() {}, fmt.Errorf("create temporary extraction root: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(temporary) }

	for _, member := range reader.File {
		name := filepath.ToSlash(filepath.Clean(member.Name))
		if _, needed := wanted[name]; !needed {
			continue
		}
		if wanted[name] {
			cleanup()
			return "", func() {}, fmt.Errorf("duplicate Schematron member %q", name)
		}
		if !member.Mode().IsRegular() || member.UncompressedSize64 > 8<<20 {
			cleanup()
			return "", func() {}, fmt.Errorf("schematron member %q is not a bounded regular file", name)
		}
		destination := filepath.Join(temporary, filepath.FromSlash(strings.TrimPrefix(name, "schematron/")))
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			cleanup()
			return "", func() {}, fmt.Errorf("create member directory: %w", err)
		}
		input, err := member.Open()
		if err != nil {
			cleanup()
			return "", func() {}, fmt.Errorf("open member %q: %w", name, err)
		}
		output, err := os.OpenFile(destination, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if err != nil {
			_ = input.Close()
			cleanup()
			return "", func() {}, fmt.Errorf("create member %q: %w", name, err)
		}
		written, copyErr := io.Copy(output, io.LimitReader(input, (8<<20)+1))
		closeOutputErr := output.Close()
		closeInputErr := input.Close()
		if copyErr != nil || closeOutputErr != nil || closeInputErr != nil || written > 8<<20 {
			cleanup()
			return "", func() {}, fmt.Errorf("extract bounded member %q", name)
		}
		wanted[name] = true
	}
	for name, found := range wanted {
		if !found {
			cleanup()
			return "", func() {}, fmt.Errorf("required Schematron member %q is missing", name)
		}
	}
	return temporary, cleanup, nil
}
